[[locations]]
file = "pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/oeselect/__init__.py"
type = "python-dunder"

[[locations]]
file = "python/oeselect/__init__.py"
type = "python-version-info"

[[locations]]
file = "CMakeLists.txt"
type = "cmake-project"

[[locations]]
file = "include/oeselect/oeselect.h"
type = "c-define"
prefix = "OESELECT"

[[locations]]
file = "swig/oeselect.i"
type = "c-define"
prefix = "OESELECT"

[[locations]]
file = "swig/oeselect.i"
type = "custom"
template = '__version__ = "{version}"'
label = "swig-python-version"

[[locations]]
file = "docs/conf.py"
type = "custom"
template = "release = '{version}'"
label = "docs-release"
