# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _oeselect
else:
    import _oeselect

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oeselect.delete_SwigPyIterator

    def value(self):
        return _oeselect.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _oeselect.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _oeselect.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _oeselect.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _oeselect.SwigPyIterator_equal(self, x)

    def copy(self):
        return _oeselect.SwigPyIterator_copy(self)

    def next(self):
        return _oeselect.SwigPyIterator_next(self)

    def __next__(self):
        return _oeselect.SwigPyIterator___next__(self)

    def previous(self):
        return _oeselect.SwigPyIterator_previous(self)

    def advance(self, n):
        return _oeselect.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _oeselect.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _oeselect.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _oeselect.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _oeselect.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _oeselect.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _oeselect.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _oeselect:
_oeselect.SwigPyIterator_swigregister(SwigPyIterator)
class UnsignedIntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oeselect.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oeselect.UnsignedIntVector___nonzero__(self)

    def __bool__(self):
        return _oeselect.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _oeselect.UnsignedIntVector___len__(self)

    def __getslice__(self, i, j):
        return _oeselect.UnsignedIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oeselect.UnsignedIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oeselect.UnsignedIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oeselect.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oeselect.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oeselect.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _oeselect.UnsignedIntVector_pop(self)

    def append(self, x):
        return _oeselect.UnsignedIntVector_append(self, x)

    def empty(self):
        return _oeselect.UnsignedIntVector_empty(self)

    def size(self):
        return _oeselect.UnsignedIntVector_size(self)

    def swap(self, v):
        return _oeselect.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _oeselect.UnsignedIntVector_begin(self)

    def end(self):
        return _oeselect.UnsignedIntVector_end(self)

    def rbegin(self):
        return _oeselect.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _oeselect.UnsignedIntVector_rend(self)

    def clear(self):
        return _oeselect.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _oeselect.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _oeselect.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _oeselect.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        _oeselect.UnsignedIntVector_swiginit(self, _oeselect.new_UnsignedIntVector(*args))

    def push_back(self, x):
        return _oeselect.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _oeselect.UnsignedIntVector_front(self)

    def back(self):
        return _oeselect.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _oeselect.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _oeselect.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _oeselect.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _oeselect.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _oeselect.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _oeselect.delete_UnsignedIntVector

# Register UnsignedIntVector in _oeselect:
_oeselect.UnsignedIntVector_swigregister(UnsignedIntVector)
OESELECT_VERSION_MAJOR = _oeselect.OESELECT_VERSION_MAJOR
OESELECT_VERSION_MINOR = _oeselect.OESELECT_VERSION_MINOR
OESELECT_VERSION_PATCH = _oeselect.OESELECT_VERSION_PATCH
PredicateType_And = _oeselect.PredicateType_And
PredicateType_Or = _oeselect.PredicateType_Or
PredicateType_Not = _oeselect.PredicateType_Not
PredicateType_XOr = _oeselect.PredicateType_XOr
PredicateType_Name = _oeselect.PredicateType_Name
PredicateType_Resn = _oeselect.PredicateType_Resn
PredicateType_Resi = _oeselect.PredicateType_Resi
PredicateType_Chain = _oeselect.PredicateType_Chain
PredicateType_Elem = _oeselect.PredicateType_Elem
PredicateType_Index = _oeselect.PredicateType_Index
PredicateType_SecondaryStructure = _oeselect.PredicateType_SecondaryStructure
PredicateType_Protein = _oeselect.PredicateType_Protein
PredicateType_Ligand = _oeselect.PredicateType_Ligand
PredicateType_Water = _oeselect.PredicateType_Water
PredicateType_Solvent = _oeselect.PredicateType_Solvent
PredicateType_Organic = _oeselect.PredicateType_Organic
PredicateType_Backbone = _oeselect.PredicateType_Backbone
PredicateType_Metal = _oeselect.PredicateType_Metal
PredicateType_Heavy = _oeselect.PredicateType_Heavy
PredicateType_Hydrogen = _oeselect.PredicateType_Hydrogen
PredicateType_PolarHydrogen = _oeselect.PredicateType_PolarHydrogen
PredicateType_NonpolarHydrogen = _oeselect.PredicateType_NonpolarHydrogen
PredicateType_ByRes = _oeselect.PredicateType_ByRes
PredicateType_ByChain = _oeselect.PredicateType_ByChain
PredicateType_Around = _oeselect.PredicateType_Around
PredicateType_XAround = _oeselect.PredicateType_XAround
PredicateType_Box = _oeselect.PredicateType_Box
PredicateType_XBox = _oeselect.PredicateType_XBox
PredicateType_Beyond = _oeselect.PredicateType_Beyond
PredicateType_Helix = _oeselect.PredicateType_Helix
PredicateType_Sheet = _oeselect.PredicateType_Sheet
PredicateType_Turn = _oeselect.PredicateType_Turn
PredicateType_Loop = _oeselect.PredicateType_Loop
PredicateType_True = _oeselect.PredicateType_True
PredicateType_False = _oeselect.PredicateType_False
class SelectionError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.SelectionError_swiginit(self, _oeselect.new_SelectionError(*args))

    def position(self):
        return _oeselect.SelectionError_position(self)
    __swig_destroy__ = _oeselect.delete_SelectionError

# Register SelectionError in _oeselect:
_oeselect.SelectionError_swigregister(SelectionError)
class OESelection(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def Parse(sele):
        return _oeselect.OESelection_Parse(sele)

    def __init__(self, *args):
        _oeselect.OESelection_swiginit(self, _oeselect.new_OESelection(*args))
    __swig_destroy__ = _oeselect.delete_OESelection

    def ToCanonical(self):
        return _oeselect.OESelection_ToCanonical(self)

    def ContainsPredicate(self, type):
        return _oeselect.OESelection_ContainsPredicate(self, type)

    def IsEmpty(self):
        return _oeselect.OESelection_IsEmpty(self)

    def __repr__(self):
        return f"OESelection('{self.ToCanonical()}')"

    def __str__(self):
        return self.ToCanonical()


# Register OESelection in _oeselect:
_oeselect.OESelection_swigregister(OESelection)

def EvaluateSelection(selection_str, smiles):
    return _oeselect.EvaluateSelection(selection_str, smiles)

def CountSelection(selection_str, smiles):
    return _oeselect.CountSelection(selection_str, smiles)

def select(selection_str, mol):
    """Evaluate a selection string on an OpenEye molecule.

    :param selection_str: PyMOL-style selection string (e.g., "name CA", "protein and chain A").
    :param mol: An OpenEye OEMolBase object (OEMol, OEGraphMol, etc.).
    :returns: List of atom indices that match the selection.

    Example::

        from openeye import oechem
        from oeselect_lib import select

        mol = oechem.OEGraphMol()
        oechem.OESmilesToMol(mol, "CC(=O)OC1=CC=CC=C1C(=O)O")  # Aspirin

# Select all carbon atoms
        carbon_indices = select("elem C", mol)

# Select backbone atoms in chain A
        bb_indices = select("backbone and chain A", mol)
    """
    from openeye import oechem
    smiles = oechem.OEMolToSmiles(mol)
    return list(EvaluateSelection(selection_str, smiles))

def count(selection_str, mol):
    """Count atoms matching a selection in an OpenEye molecule.

    :param selection_str: PyMOL-style selection string.
    :param mol: An OpenEye OEMolBase object.
    :returns: Number of atoms matching the selection.

    Example::

        num_carbons = count("elem C", mol)
    """
    from openeye import oechem
    smiles = oechem.OEMolToSmiles(mol)
    return CountSelection(selection_str, smiles)

def parse(selection_str):
    """Parse a selection string and return an OESelection object.

    :param selection_str: PyMOL-style selection string.
    :returns: OESelection object that can be used for validation and canonicalization.
    :raises ValueError: If the selection string is invalid.

    Example::

        sele = parse("name CA and protein")
        print(sele.ToCanonical())  # Normalized form
    """
    return OESelection.Parse(selection_str)

__version__ = "1.0.0"


