# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _oeselect
else:
    import _oeselect

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oeselect.delete_SwigPyIterator

    def value(self):
        return _oeselect.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _oeselect.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _oeselect.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _oeselect.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _oeselect.SwigPyIterator_equal(self, x)

    def copy(self):
        return _oeselect.SwigPyIterator_copy(self)

    def next(self):
        return _oeselect.SwigPyIterator_next(self)

    def __next__(self):
        return _oeselect.SwigPyIterator___next__(self)

    def previous(self):
        return _oeselect.SwigPyIterator_previous(self)

    def advance(self, n):
        return _oeselect.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _oeselect.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _oeselect.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _oeselect.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _oeselect.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _oeselect.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _oeselect.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _oeselect:
_oeselect.SwigPyIterator_swigregister(SwigPyIterator)
class UnsignedIntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oeselect.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oeselect.UnsignedIntVector___nonzero__(self)

    def __bool__(self):
        return _oeselect.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _oeselect.UnsignedIntVector___len__(self)

    def __getslice__(self, i, j):
        return _oeselect.UnsignedIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oeselect.UnsignedIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oeselect.UnsignedIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oeselect.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oeselect.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oeselect.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _oeselect.UnsignedIntVector_pop(self)

    def append(self, x):
        return _oeselect.UnsignedIntVector_append(self, x)

    def empty(self):
        return _oeselect.UnsignedIntVector_empty(self)

    def size(self):
        return _oeselect.UnsignedIntVector_size(self)

    def swap(self, v):
        return _oeselect.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _oeselect.UnsignedIntVector_begin(self)

    def end(self):
        return _oeselect.UnsignedIntVector_end(self)

    def rbegin(self):
        return _oeselect.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _oeselect.UnsignedIntVector_rend(self)

    def clear(self):
        return _oeselect.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _oeselect.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _oeselect.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _oeselect.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        _oeselect.UnsignedIntVector_swiginit(self, _oeselect.new_UnsignedIntVector(*args))

    def push_back(self, x):
        return _oeselect.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _oeselect.UnsignedIntVector_front(self)

    def back(self):
        return _oeselect.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _oeselect.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _oeselect.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _oeselect.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _oeselect.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _oeselect.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _oeselect.delete_UnsignedIntVector

# Register UnsignedIntVector in _oeselect:
_oeselect.UnsignedIntVector_swigregister(UnsignedIntVector)
class SelectorSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oeselect.SelectorSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oeselect.SelectorSet___nonzero__(self)

    def __bool__(self):
        return _oeselect.SelectorSet___bool__(self)

    def __len__(self):
        return _oeselect.SelectorSet___len__(self)

    def append(self, x):
        return _oeselect.SelectorSet_append(self, x)

    def __contains__(self, x):
        return _oeselect.SelectorSet___contains__(self, x)

    def __getitem__(self, i):
        return _oeselect.SelectorSet___getitem__(self, i)

    def add(self, x):
        return _oeselect.SelectorSet_add(self, x)

    def discard(self, x):
        return _oeselect.SelectorSet_discard(self, x)

    def __init__(self, *args):
        _oeselect.SelectorSet_swiginit(self, _oeselect.new_SelectorSet(*args))

    def empty(self):
        return _oeselect.SelectorSet_empty(self)

    def size(self):
        return _oeselect.SelectorSet_size(self)

    def clear(self):
        return _oeselect.SelectorSet_clear(self)

    def swap(self, v):
        return _oeselect.SelectorSet_swap(self, v)

    def count(self, x):
        return _oeselect.SelectorSet_count(self, x)

    def begin(self):
        return _oeselect.SelectorSet_begin(self)

    def end(self):
        return _oeselect.SelectorSet_end(self)

    def rbegin(self):
        return _oeselect.SelectorSet_rbegin(self)

    def rend(self):
        return _oeselect.SelectorSet_rend(self)

    def erase(self, *args):
        return _oeselect.SelectorSet_erase(self, *args)

    def find(self, x):
        return _oeselect.SelectorSet_find(self, x)

    def lower_bound(self, x):
        return _oeselect.SelectorSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _oeselect.SelectorSet_upper_bound(self, x)

    def equal_range(self, x):
        return _oeselect.SelectorSet_equal_range(self, x)

    def insert(self, __x):
        return _oeselect.SelectorSet_insert(self, __x)
    __swig_destroy__ = _oeselect.delete_SelectorSet

# Register SelectorSet in _oeselect:
_oeselect.SelectorSet_swigregister(SelectorSet)
class StringSet(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oeselect.StringSet_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oeselect.StringSet___nonzero__(self)

    def __bool__(self):
        return _oeselect.StringSet___bool__(self)

    def __len__(self):
        return _oeselect.StringSet___len__(self)

    def append(self, x):
        return _oeselect.StringSet_append(self, x)

    def __contains__(self, x):
        return _oeselect.StringSet___contains__(self, x)

    def __getitem__(self, i):
        return _oeselect.StringSet___getitem__(self, i)

    def add(self, x):
        return _oeselect.StringSet_add(self, x)

    def discard(self, x):
        return _oeselect.StringSet_discard(self, x)

    def __init__(self, *args):
        _oeselect.StringSet_swiginit(self, _oeselect.new_StringSet(*args))

    def empty(self):
        return _oeselect.StringSet_empty(self)

    def size(self):
        return _oeselect.StringSet_size(self)

    def clear(self):
        return _oeselect.StringSet_clear(self)

    def swap(self, v):
        return _oeselect.StringSet_swap(self, v)

    def count(self, x):
        return _oeselect.StringSet_count(self, x)

    def begin(self):
        return _oeselect.StringSet_begin(self)

    def end(self):
        return _oeselect.StringSet_end(self)

    def rbegin(self):
        return _oeselect.StringSet_rbegin(self)

    def rend(self):
        return _oeselect.StringSet_rend(self)

    def erase(self, *args):
        return _oeselect.StringSet_erase(self, *args)

    def find(self, x):
        return _oeselect.StringSet_find(self, x)

    def lower_bound(self, x):
        return _oeselect.StringSet_lower_bound(self, x)

    def upper_bound(self, x):
        return _oeselect.StringSet_upper_bound(self, x)

    def equal_range(self, x):
        return _oeselect.StringSet_equal_range(self, x)

    def insert(self, __x):
        return _oeselect.StringSet_insert(self, __x)
    __swig_destroy__ = _oeselect.delete_StringSet

# Register StringSet in _oeselect:
_oeselect.StringSet_swigregister(StringSet)
OESELECT_VERSION_MAJOR = _oeselect.OESELECT_VERSION_MAJOR
OESELECT_VERSION_MINOR = _oeselect.OESELECT_VERSION_MINOR
OESELECT_VERSION_PATCH = _oeselect.OESELECT_VERSION_PATCH
PredicateType_AND = _oeselect.PredicateType_AND
PredicateType_OR = _oeselect.PredicateType_OR
PredicateType_NOT = _oeselect.PredicateType_NOT
PredicateType_XOR = _oeselect.PredicateType_XOR
PredicateType_NAME = _oeselect.PredicateType_NAME
PredicateType_RESN = _oeselect.PredicateType_RESN
PredicateType_RESI = _oeselect.PredicateType_RESI
PredicateType_CHAIN = _oeselect.PredicateType_CHAIN
PredicateType_ELEM = _oeselect.PredicateType_ELEM
PredicateType_INDEX = _oeselect.PredicateType_INDEX
PredicateType_ID = _oeselect.PredicateType_ID
PredicateType_ALT = _oeselect.PredicateType_ALT
PredicateType_B_FACTOR = _oeselect.PredicateType_B_FACTOR
PredicateType_FRAGMENT = _oeselect.PredicateType_FRAGMENT
PredicateType_SECONDARY_STRUCTURE = _oeselect.PredicateType_SECONDARY_STRUCTURE
PredicateType_PROTEIN = _oeselect.PredicateType_PROTEIN
PredicateType_LIGAND = _oeselect.PredicateType_LIGAND
PredicateType_WATER = _oeselect.PredicateType_WATER
PredicateType_SOLVENT = _oeselect.PredicateType_SOLVENT
PredicateType_ORGANIC = _oeselect.PredicateType_ORGANIC
PredicateType_BACKBONE = _oeselect.PredicateType_BACKBONE
PredicateType_METAL = _oeselect.PredicateType_METAL
PredicateType_HEAVY = _oeselect.PredicateType_HEAVY
PredicateType_HYDROGEN = _oeselect.PredicateType_HYDROGEN
PredicateType_POLAR_HYDROGEN = _oeselect.PredicateType_POLAR_HYDROGEN
PredicateType_NONPOLAR_HYDROGEN = _oeselect.PredicateType_NONPOLAR_HYDROGEN
PredicateType_BY_RES = _oeselect.PredicateType_BY_RES
PredicateType_BY_CHAIN = _oeselect.PredicateType_BY_CHAIN
PredicateType_AROUND = _oeselect.PredicateType_AROUND
PredicateType_EXPAND = _oeselect.PredicateType_EXPAND
PredicateType_BEYOND = _oeselect.PredicateType_BEYOND
PredicateType_HELIX = _oeselect.PredicateType_HELIX
PredicateType_SHEET = _oeselect.PredicateType_SHEET
PredicateType_TURN = _oeselect.PredicateType_TURN
PredicateType_LOOP = _oeselect.PredicateType_LOOP
PredicateType_TRUE = _oeselect.PredicateType_TRUE
PredicateType_FALSE = _oeselect.PredicateType_FALSE
class SelectionError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.SelectionError_swiginit(self, _oeselect.new_SelectionError(*args))

    def Position(self):
        return _oeselect.SelectionError_Position(self)
    __swig_destroy__ = _oeselect.delete_SelectionError

# Register SelectionError in _oeselect:
_oeselect.SelectionError_swigregister(SelectionError)
class OESelection(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def Parse(sele):
        return _oeselect.OESelection_Parse(sele)

    def __init__(self, *args):
        _oeselect.OESelection_swiginit(self, _oeselect.new_OESelection(*args))
    __swig_destroy__ = _oeselect.delete_OESelection

    def ToCanonical(self):
        return _oeselect.OESelection_ToCanonical(self)

    def ContainsPredicate(self, type):
        return _oeselect.OESelection_ContainsPredicate(self, type)

    def IsEmpty(self):
        return _oeselect.OESelection_IsEmpty(self)

    def __repr__(self):
        return f"OESelection('{self.ToCanonical()}')"

    def __str__(self):
        return self.ToCanonical()


# Register OESelection in _oeselect:
_oeselect.OESelection_swigregister(OESelection)
class OESelect(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.OESelect_swiginit(self, _oeselect.new_OESelect(*args))
    __swig_destroy__ = _oeselect.delete_OESelect

    def __call__(self, atom):
        return _oeselect.OESelect___call__(self, atom)

    def GetSelection(self):
        return _oeselect.OESelect_GetSelection(self)

    def __repr__(self):
        return f"OESelect('{self.GetSelection().ToCanonical()}')"


# Register OESelect in _oeselect:
_oeselect.OESelect_swigregister(OESelect)
class Selector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_oeselect.Selector_name_get, _oeselect.Selector_name_set)
    residue_number = property(_oeselect.Selector_residue_number_get, _oeselect.Selector_residue_number_set)
    chain = property(_oeselect.Selector_chain_get, _oeselect.Selector_chain_set)
    insert_code = property(_oeselect.Selector_insert_code_get, _oeselect.Selector_insert_code_set)

    def __init__(self, *args):
        _oeselect.Selector_swiginit(self, _oeselect.new_Selector(*args))

    @staticmethod
    def FromAtom(atom):
        return _oeselect.Selector_FromAtom(atom)

    @staticmethod
    def FromString(selector_str):
        return _oeselect.Selector_FromString(selector_str)

    def ToString(self):
        return _oeselect.Selector_ToString(self)

    def __lt__(self, other):
        return _oeselect.Selector___lt__(self, other)

    def __gt__(self, other):
        return _oeselect.Selector___gt__(self, other)

    def __le__(self, other):
        return _oeselect.Selector___le__(self, other)

    def __ge__(self, other):
        return _oeselect.Selector___ge__(self, other)

    def __eq__(self, other):
        return _oeselect.Selector___eq__(self, other)

    def __ne__(self, other):
        return _oeselect.Selector___ne__(self, other)

    def __repr__(self):
        return f"Selector('{self.ToString()}')"

    def __str__(self):
        return self.ToString()

    def __hash__(self):
        return hash((self.name, self.residue_number, self.chain, self.insert_code))

    __swig_destroy__ = _oeselect.delete_Selector

# Register Selector in _oeselect:
_oeselect.Selector_swigregister(Selector)
class OEResidueSelector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.OEResidueSelector_swiginit(self, _oeselect.new_OEResidueSelector(*args))
    __swig_destroy__ = _oeselect.delete_OEResidueSelector

    def __call__(self, atom):
        return _oeselect.OEResidueSelector___call__(self, atom)

# Register OEResidueSelector in _oeselect:
_oeselect.OEResidueSelector_swigregister(OEResidueSelector)
class OEHasResidueName(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.OEHasResidueName_swiginit(self, _oeselect.new_OEHasResidueName(*args))
    __swig_destroy__ = _oeselect.delete_OEHasResidueName

    def __call__(self, atom):
        return _oeselect.OEHasResidueName___call__(self, atom)

# Register OEHasResidueName in _oeselect:
_oeselect.OEHasResidueName_swigregister(OEHasResidueName)
class OEHasAtomNameAdvanced(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oeselect.OEHasAtomNameAdvanced_swiginit(self, _oeselect.new_OEHasAtomNameAdvanced(*args))
    __swig_destroy__ = _oeselect.delete_OEHasAtomNameAdvanced

    def __call__(self, atom):
        return _oeselect.OEHasAtomNameAdvanced___call__(self, atom)

# Register OEHasAtomNameAdvanced in _oeselect:
_oeselect.OEHasAtomNameAdvanced_swigregister(OEHasAtomNameAdvanced)

def parse_selector_set(selector_str):
    return _oeselect.parse_selector_set(selector_str)

def mol_to_selector_set(mol):
    return _oeselect.mol_to_selector_set(mol)

def str_selector_set(mol, selection_str):
    return _oeselect.str_selector_set(mol, selection_str)

def get_selector_string(atom):
    return _oeselect.get_selector_string(atom)

def EvaluateSelection(mol, selection_str):
    return _oeselect.EvaluateSelection(mol, selection_str)

def CountSelection(mol, selection_str):
    return _oeselect.CountSelection(mol, selection_str)

def select(mol, selection_str):
    """Evaluate a selection string on an OpenEye molecule.

    :param mol: An OpenEye OEMolBase object (OEMol, OEGraphMol, etc.).
    :param selection_str: PyMOL-style selection string (e.g., "name CA", "protein and chain A").
    :returns: List of atom indices that match the selection.

    Example::

        from openeye import oechem
        from oeselect import select

        mol = oechem.OEGraphMol()
        oechem.OESmilesToMol(mol, "CC(=O)OC1=CC=CC=C1C(=O)O")  # Aspirin

# Select all carbon atoms
        carbon_indices = select(mol, "elem C")

# Select backbone atoms in chain A
        bb_indices = select(mol, "backbone and chain A")
    """
    return list(EvaluateSelection(mol, selection_str))

def count(mol, selection_str):
    """Count atoms matching a selection in an OpenEye molecule.

    :param mol: An OpenEye OEMolBase object.
    :param selection_str: PyMOL-style selection string.
    :returns: Number of atoms matching the selection.

    Example::

        num_carbons = count(mol, "elem C")
    """
    return CountSelection(mol, selection_str)

def parse(selection_str):
    """Parse a selection string and return an OESelection object.

    :param selection_str: PyMOL-style selection string.
    :returns: OESelection object that can be used for validation and canonicalization.
    :raises ValueError: If the selection string is invalid.

    Example::

        sele = parse("name CA and protein")
        print(sele.ToCanonical())  # Normalized form
    """
    return OESelection.Parse(selection_str)

def str_selector_set(mol, selection_str):
    """Extract unique residue selector strings for atoms matching a selection.

    :param mol: An OpenEye OEMolBase object.
    :param selection_str: PyMOL-style selection string.
    :returns: Set of unique selector strings in "NAME:NUMBER:ICODE:CHAIN" format.

    Example::

        selectors = str_selector_set(mol, "protein")
    """
    return str_selector_set(mol, selection_str)

def selector_set(selector_str):
    """Parse a selector string into a set of Selector objects.

    :param selector_str: Comma/semicolon/newline-separated selector strings.
    :returns: Set of Selector objects.

    Example::

        sels = selector_set("ALA:123: :A,GLY:124: :A")
    """
    return parse_selector_set(selector_str)

def mol_to_selector_set(mol):
    """Extract unique Selector objects from all atoms in a molecule.

    :param mol: An OpenEye OEMolBase object.
    :returns: Set of Selector objects for all unique residues.

    Example::

        selectors = mol_to_selector_set(mol)
    """
    return mol_to_selector_set(mol)

def get_selector_string(atom):
    """Get the selector string for an atom.

    :param atom: An OpenEye OEAtomBase object.
    :returns: Selector string in "NAME:NUMBER:ICODE:CHAIN" format.

    Example::

        for atom in mol.GetAtoms():
            print(get_selector_string(atom))
    """
    return get_selector_string(atom)

__version__ = "1.0.0"


